### ISSUE TITLE
I want tacky to color the border with the accent color, but I don't know how 

### ISSUE THREAD

**Issue by Dhyfer1** [lukeyou05/tacky-borders#25]
Hi @lukeyou05 👋

Thank you for such an incredible program, I like it a lot. 

Well, as the title says. I want tacky-bordes to color the border of the active window to the system accent color, like cute borders can do, but I don't understand how to do it. Or rather, maybe I understand but tacky-bordes shows me an error window

This is the default configuration as it appears in the yaml file:

```yaml
# active_color: the color of the active window's border
  # inactive_color: the color of the inactive window's border
  #
  # Supported color types:
  #   - Solid: Use a hex code or "accent"
  #       Example:
  #         active_color: "#ffffff"
  #         OR
  #         active_color: "accent"
  #   - Gradient: Define colors and direction
  #       Example:
  #         active_color:
  #           colors: ["#000000", "#ffffff"]
  #           direction: 45deg
  #         OR
  #         active_color:
  #           colors: ["#000000", "#ffffff"]
  #           direction:
  #             start: [0.0, 1.0]
  #             end: [1.0, 0.0]
  #       NOTE: [0.0, 0.0] = top-left, [1.0, 1.0] = bottom-right
  active_color:
    colors: ["#6274e7", "#8752a3"]
    direction: 45deg

  inactive_color:
    colors: ["#30304f", "#363c69"]
    direction:
      start: [0.0, 1.0]
      end: [1.0, 0.0]
```

How I want tacky to color the border of the active window with the system accent color, I set it like this:

```yaml
active_color:
    colors: "accent"
    direction:
```
As you can see, I put "accent" as the example shows and deleted the value that was next to it, since the system accent color is only one. And I also removed the value in direction since I'm not going to use gradients, just the system accent color. But after saving the file this window appears

![Screenshot 2025-03-10 212746.png](https://github.com/user-attachments/assets/9f7f9173-8296-43f6-840c-c0f671a31d79)

I thought the problem was because I didn't put "accent" inside brackets, for example ["accent"], but still tacky threw me the same error window.

So what is the correct setting to make tacky display the accent color on the border of the active window?
